/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel-plugin for production.
 */
const documents = {
    "\n    query Login($options: UsernamePasswordInput!) {\n        login(options: $options) {\n            user {\n               _id\n                createdAt\n                updatedAt\n                email\n                firstName\n                lastName\n                churchName\n                dob\n                count\n                bioText\n            }\n            errors {\n              field\n              message\n            }\n        }\n    }\n": types.LoginDocument,
    "\n    mutation Register($options: UsernamePasswordInput!) {\n      register(options: $options) {\n        user {\n          _id\n          createdAt\n          updatedAt\n          email\n          firstName\n          lastName\n          churchName\n          dob\n          count\n          bioText\n        }\n        errors {\n          field\n          message\n        }\n      }\n    }\n": types.RegisterDocument,
    "\n    mutation LoginWithGoogleMutation($options: LogInWithGoogleArgs!) {\n      loginWithGoogle(options: $options) {\n        user {\n          _id\n          createdAt\n          updatedAt\n          email\n          firstName\n          lastName\n          churchName\n          dob\n          count\n          bioText\n        }\n        errors {\n          field\n          message\n        }\n      }\n    }\n": types.LoginWithGoogleMutationDocument,
    "\n    query GetListOfLanguages($options: LanguagesArgs!) {\n        getListOfLanguages(options: $options) {\n            data {\n                id\n                glottoId\n                iso\n                name\n                autonym\n                bibles\n                filesets\n                rolvCode\n                countryPopulation\n                translations\n            }\n            meta {\n                pagination {\n                    total\n                    count\n                    perPage\n                    currentPage\n                    totalPages\n                    links\n                    lastPage\n                    nextPageUrl\n                    prevPageUrl\n                    from\n                    to\n                }\n            }\n        }\n    }\n": types.GetListOfLanguagesDocument,
    "\n  query SearchLangueages($options: SearchLanguageArgs!) {\n    searchListOfLanguages(options: $options) {\n      data {\n        id\n        glottoId\n        iso\n        name\n        autonym\n        bibles\n        rolvCode\n      }\n      meta {\n        pagination {\n          total\n          count\n          perPage\n          currentPage\n          totalPages\n          links\n        }\n      }\n    }\n  }\n": types.SearchLangueagesDocument,
    "\n    query GetListOfBibles($options: BibleArgs!) {\n        getListOFBibles(options: $options){\n            data {\n                name\n                vname\n                abbr\n                language\n                autonym\n                languageId\n                iso\n                date\n                filesets\n            }\n            meta {\n                pagination {\n                    total\n                    count\n                    from\n                    to\n                    nextPageUrl\n                    perPage\n                    prevPageUrl\n                    totalPages\n                    lastPage\n                    currentPage\n                    links\n                }\n            }\n        }\n    }\n": types.GetListOfBiblesDocument,
    "\n    query GetListOfBooksFromBible($options: BookArgs!) {\n        getListOfBooksForBible(options: $options) {\n            data {\n                bookId\n                bookIdUsfx\n                bookIdOsis\n                name\n                testament\n                testamentOrder\n                bookOrder\n                bookGroup\n                nameShort\n                chapters\n                contentTypes\n            }\n        }\n    }\n": types.GetListOfBooksFromBibleDocument,
    "\n    query GetListOfVerseFromBookChapter($options: VerseArgs!) {\n        getListOfVerseFromBookChapter(options: $options){\n            data {\n                bookId\n                bookName\n                bookNameAlt\n                chapter\n                chapterAlt\n                verseStart\n                verseStartAlt\n                verseEnd\n                verseEndAlt\n                verseText\n            } \n        }\n    }\n": types.GetListOfVerseFromBookChapterDocument,
    "\n  query GetCopyRightByBibleId($options: CopyrightArgs!) {\n    getCopyRightByBibleId(options: $options) {\n      data {\n        id\n        asset_id\n        type\n        size\n        copyright {\n          copyright_date\n          copyright\n          copyright_description\n          created_at\n          updated_at\n          open_access\n          organizations {\n            id\n            slug\n            abbreviation\n            primaryColor\n            secondaryColor\n            inactive\n            url_facebook\n            url_website\n            url_donate\n            url_twitter\n            address\n            address2\n            city\n            state\n            country\n            zip\n            phone\n            email\n            email_director\n            latitude\n            longitude\n            laravel_through_key\n            logos {\n              language_id\n              language_iso\n              url\n              icon\n            }\n            translations {\n              language_id\n              vernacular\n              alt\n              name\n              description_short\n            }\n          }\n        }\n      }\n    }\n  }\n": types.GetCopyRightByBibleIdDocument,
    "\n  query GetAudioMedia($options: AudioMediaArgs!) {\n    getAudioMedia(options: $options) {\n      data {\n        book_id\n        book_name\n        chapter_start\n        chapter_end\n        verse_start\n        verse_end\n        thumbnail\n        timestamp\n        path\n        duration\n      }\n    }\n  }\n": types.GetAudioMediaDocument,
    "\n  query GetMediaTimestamps($options: AudioMediaArgs!) {\n    getMediaTimestamps(options: $options) {\n      data {\n        book\n        chapter\n        verse_start\n        timestamp\n      }\n    }\n  }\n": types.GetMediaTimestampsDocument,
    "\n  query GetTranslations {\n    getTranslations {\n      _id\n      name\n      abbreviation\n      language\n      lang\n      books {\n        bookName\n        bibleId\n      }\n    }\n  }\n": types.GetTranslationsDocument,
    "\n  query GetBooks($translationId: String!) {\n    getBooks(translationId: $translationId) {\n      bookName\n      bibleId\n    }\n  }\n": types.GetBooksDocument,
    "\n  query GetBookById($bibleId: String!) {\n  getBookById(bibleId: $bibleId) {\n    _id\n    bookName\n    bibleId\n    chapters {\n      chapterName\n      bibleId\n    }\n    translation {\n      abbreviation\n      name\n    }\n  }\n}\n": types.GetBookByIdDocument,
    "\n  query GetChapter($bibleId: String!) {\n    getChapter(bibleId: $bibleId) {\n      _id\n      chapterNumber\n      bibleId\n      bookName\n      verses {\n        verse\n        bibleId\n        text\n      }\n      translation {\n        abbreviation\n        name\n      }\n    }\n  }\n": types.GetChapterDocument,
    "\n  query GetVerseById($bibleId: String!) {\n    getVerseByBibleId(bibleId: $bibleId) {\n      _id\n      translation {\n        name\n        abbreviation\n      }\n      bookName\n      chapterNumber\n      verse\n      text\n      bibleId\n    }\n  }\n": types.GetVerseByIdDocument,
    "\n  mutation SetUserHistory($options: HistoryOptions!) {\n    setUserHistory(options: $options) {\n      errors {\n        field\n        message\n      }\n      results\n    }\n  }\n": types.SetUserHistoryDocument,
    "\n  query GetMedia($id: String!) {\n    getMedia(id: $id) {\n      _id\n      fileKey\n      filename\n      mimeType\n      size\n      purpose\n      isPublic\n      description\n      owner {\n        _id\n      }\n      cache {\n        url\n        expiresAt\n        duration\n      }\n      createdAt\n      updatedAt\n    }\n  }\n": types.GetMediaDocument,
    "\n  query GetMediaByPurpose($purpose: String!) {\n    getMediaByPurpose(purpose: $purpose) {\n      _id\n      fileKey\n      filename\n      mimeType\n      size\n      purpose\n      isPublic\n      description\n      owner {\n        _id\n      }\n      cache {\n        url\n        expiresAt\n        duration\n      }\n      createdAt\n      updatedAt\n    }\n  }\n": types.GetMediaByPurposeDocument,
    "\n  query GetMediaUrl($fileKey: String!) {\n    getMediaUrl(fileKey: $fileKey) {\n      signedUrl\n      errors {\n        field\n        message\n      }\n    }\n  }\n": types.GetMediaUrlDocument,
    "\n  mutation GetGetSignedUrl($options: SignedUrlInput!) {\n    getGetSignedUrl(options: $options) {\n      signedUrl\n      fileKey\n      errors {\n        field\n        message\n      }\n    }\n  }\n": types.GetGetSignedUrlDocument,
    "\n  mutation GetPostSignedUrl($options: SignedUrlInput!) {\n    getPostSignedUrl(options: $options) {\n      signedUrl\n      fields\n      fileKey\n      errors {\n        field\n        message\n      }\n    }\n  }\n": types.GetPostSignedUrlDocument,
    "\n  mutation CreateMedia($options: MediaInput!) {\n    createMedia(options: $options) {\n      results {\n        _id\n        fileKey\n        filename\n        mimeType\n        size\n        purpose\n        isPublic\n        description\n        owner {\n          _id\n        }\n        cache {\n          url\n          expiresAt\n          duration\n        }\n        createdAt\n        updatedAt\n      }\n      errors {\n        field\n        message\n      }\n    }\n  }\n": types.CreateMediaDocument,
    "\n  mutation UpdateMedia($id: String!, $options: MediaInput!) {\n    updateMedia(id: $id, options: $options) {\n      results {\n        _id\n        fileKey\n        filename\n        mimeType\n        size\n        purpose\n        isPublic\n        description\n        owner {\n          _id\n        }\n        cache {\n          url\n          expiresAt\n          duration\n        }\n        createdAt\n        updatedAt\n      }\n      errors {\n        field\n        message\n      }\n    }\n  }\n": types.UpdateMediaDocument,
    "\n  mutation DeleteMedia($id: String!) {\n    deleteMedia(id: $id) {\n      results {\n        _id\n        fileKey\n        filename\n        mimeType\n        size\n        purpose\n        isPublic\n        description\n        owner {\n          _id\n        }\n        cache {\n          url\n          expiresAt\n          duration\n        }\n        createdAt\n        updatedAt\n      }\n      errors {\n        field\n        message\n      }\n    }\n  }\n": types.DeleteMediaDocument,
    "\n  query GetNFCConfig($id: String!) {\n    getNFCConfig(id: $id) {\n      results {\n        _id\n        owner {\n          _id\n        }\n        nfcIds\n        tiles {\n          id\n          type\n          label\n          icon\n          url\n          size\n          position {\n            x\n            y\n          }\n          color\n          subtitle\n          isInDock\n        }\n        wallpaper\n        createdAt\n        updatedAt\n      }\n      errors {\n        field\n        message\n      }\n    }\n  }\n": types.GetNfcConfigDocument,
    "\n  query GetNFCConfigByOwner($ownerId: String!) {\n    getNFCConfigByOwner(ownerId: $ownerId) {\n      results {\n        _id\n        owner {\n          _id\n        }\n        nfcIds\n        tiles {\n          id\n          type\n          label\n          icon\n          url\n          size\n          position {\n            x\n            y\n          }\n          color\n          subtitle\n          isInDock\n        }\n        wallpaper\n        createdAt\n        updatedAt\n      }\n      errors {\n        field\n        message\n      }\n    }\n  }\n": types.GetNfcConfigByOwnerDocument,
    "\n  mutation CreateNFCConfig($options: NFCConfigInput!) {\n    createNFCConfig(options: $options) {\n      results {\n        _id\n        owner {\n          _id\n        }\n        nfcIds\n        tiles {\n          id\n          type\n          label\n          icon\n          url\n          size\n          position {\n            x\n            y\n          }\n          color\n          subtitle\n          isInDock\n        }\n        wallpaper\n        createdAt\n        updatedAt\n      }\n      errors {\n        field\n        message\n      }\n    }\n  }\n": types.CreateNfcConfigDocument,
    "\n  mutation UpdateNFCConfig($id: String!, $options: NFCConfigInput!) {\n    updateNFCConfig(id: $id, options: $options) {\n      results {\n        _id\n        owner {\n          _id\n        }\n        nfcIds\n        tiles {\n          id\n          type\n          label\n          icon\n          url\n          size\n          position {\n            x\n            y\n          }\n          color\n          subtitle\n          isInDock\n        }\n        wallpaper\n        createdAt\n        updatedAt\n      }\n      errors {\n        field\n        message\n      }\n    }\n  }\n": types.UpdateNfcConfigDocument,
    "\n  mutation UpdateNFCTiles($id: String!, $tiles: [TileConfigInput!]!, $wallpaper: String) {\n    updateNFCTiles(id: $id, tiles: $tiles, wallpaper: $wallpaper) {\n      results {\n        _id\n        tiles {\n          id\n          type\n          label\n          icon\n          url\n          size\n          position {\n            x\n            y\n          }\n          color\n          subtitle\n          isInDock\n        }\n        wallpaper\n      }\n      errors {\n        field\n        message\n      }\n    }\n  }\n": types.UpdateNfcTilesDocument,
    "\n  mutation DeleteNFCConfig($id: String!) {\n    deleteNFCConfig(id: $id) {\n      results {\n        _id\n        owner {\n          _id\n        }\n        nfcIds\n        createdAt\n        updatedAt\n      }\n      errors {\n        field\n        message\n      }\n    }\n  }\n": types.DeleteNfcConfigDocument,
    "\n    query OpenAi($options: GptArgs!) {\n        getOpen(options: $options)\n    }\n": types.OpenAiDocument,
    "\n  subscription Subscription($deviceId: String!) {\n    aiChatReponseUpdated(deviceId: $deviceId)\n  }\n": types.SubscriptionDocument,
    "\n  query GetSermons {\n    getSermons {\n      results {\n        _id\n        title\n        content\n        status\n        createdAt\n        updatedAt\n        author {\n          _id\n          firstName\n          lastName\n        }\n      }\n      errors {\n        field\n        message\n      }\n    }\n  }\n": types.GetSermonsDocument,
    "\n  query GetSermon($id: String!) {\n    getSermon(id: $id) {\n      results {\n        _id\n        title\n        content\n        status\n        createdAt\n        updatedAt\n        author {\n          _id\n          firstName\n          lastName\n        }\n      }\n      errors {\n        field\n        message\n      }\n    }\n  }\n": types.GetSermonDocument,
    "\n  mutation CreateSermon($options: SermonInput!) {\n    createSermon(options: $options) {\n      results {\n        _id\n        title\n        content\n        status\n        createdAt\n        updatedAt\n        author {\n          _id\n          firstName\n          lastName\n        }\n      }\n      errors {\n        field\n        message\n      }\n    }\n  }\n": types.CreateSermonDocument,
    "\n  mutation UpdateSermon($id: String!, $options: SermonInput!) {\n    updateSermon(id: $id, options: $options) {\n      results {\n        _id\n        title\n        content\n        status\n        createdAt\n        updatedAt\n        author {\n          _id\n          firstName\n          lastName\n        }\n      }\n      errors {\n        field\n        message\n      }\n    }\n  }\n": types.UpdateSermonDocument,
    "\n  mutation DeleteSermon($id: String!) {\n    deleteSermon(id: $id) {\n      results {\n        _id\n        title\n      }\n      errors {\n        field\n        message\n      }\n    }\n  }\n": types.DeleteSermonDocument,
    "\n  mutation GenerateSermonContent($input: SermonAIInput!) {\n    generateSermonContent(input: $input) {\n      result {\n        content\n        suggestions\n        relatedVerses\n        promptType\n      }\n      errors {\n        message\n      }\n    }\n  }\n": types.GenerateSermonContentDocument,
    "\n  query GetSermonAIPromptTypes {\n    getSermonAIPromptTypes {\n      type\n      category\n      label\n      description\n    }\n  }\n": types.GetSermonAiPromptTypesDocument,
    "\n  mutation StreamSermonContent($input: SermonAIInput!) {\n    streamSermonContent(input: $input)\n  }\n": types.StreamSermonContentDocument,
    "\n  subscription SermonAIStream($sessionId: String!) {\n    sermonAIStream(sessionId: $sessionId)\n  }\n": types.SermonAiStreamDocument,
    "\n    query Me {\n        me {\n            user {\n              _id\n              createdAt\n              updatedAt\n              email\n              firstName\n              lastName\n              churchName\n              bioText\n              dob\n              count\n            }\n        }\n    }\n": types.MeDocument,
    "\n    query UserBibleHistoryQuery {\n        me {\n          user{\n            bibleHistory {\n              _id\n              history {\n                language\n                bibleAbbr\n                bookId\n                chapterNumber\n                viewedAt\n              }\n              current\n              createdAt\n              updatedAt\n            }\n          }\n        }\n    }\n": types.UserBibleHistoryQueryDocument,
    "\n  query getBookmarks {\n    getMyBookmarks {\n      results {\n        _id\n        createdAt\n        updatedAt\n        author {\n          _id\n        }\n        bibleId\n        newVerses {\n          bookId\n          bookName\n          bookNameAlt\n          chapter\n          chapterAlt\n          verseStart\n          verseStartAlt\n          verseEnd\n          verseEndAlt\n          verseText\n        }\n        verses {\n          _id\n          translation {\n            name\n            abbreviation\n          }\n          bookName\n          chapterNumber\n          verse\n          text\n          bibleId\n        }\n        note\n      }\n    }\n  }\n": types.GetBookmarksDocument,
    "\n  mutation CreateBookmark($options: BookmarkOptions!) {\n    createBookmark(options: $options) {\n      results {\n        _id\n        createdAt\n        updatedAt\n        author {\n          _id\n          createdAt\n          updatedAt\n          email\n          firstName\n          lastName\n          churchName\n          dob\n          count\n          bookmarks {\n            _id\n            createdAt\n            updatedAt\n            bibleId\n            note\n          }\n          bioText\n        }\n        bibleId\n        newVerses {\n          bookId\n          bookName\n          bookNameAlt\n          chapter\n          chapterAlt\n          verseStart\n          verseStartAlt\n          verseEnd\n          verseEndAlt\n          verseText\n        }\n        verses {\n          _id\n          translation {\n            name\n            abbreviation\n          }\n          bookName\n          chapterNumber\n          verse\n          text\n          bibleId\n        }\n        note\n      }\n    }\n  }\n": types.CreateBookmarkDocument,
    "\n  mutation UpdateUser($options: UserUpdateInput!) {\n    updateUser(options: $options) {\n      user {\n        _id\n        createdAt\n        updatedAt\n        email\n        firstName\n        lastName\n        churchName\n        bioText\n        dob\n        count\n      }\n      errors {\n        field\n        message\n      }\n    }\n  }\n": types.UpdateUserDocument,
    "\n  mutation UpdateBookmark($updateBookmarkId: String!, $options: BookmarkOptions!) {\n    updateBookmark(id: $updateBookmarkId, options: $options) {\n      errors {\n        field\n        message\n      }\n      results {\n        _id\n        createdAt\n        updatedAt\n        author {\n          _id\n        }\n        note\n        verses {\n          _id\n        }\n      }\n    }\n  }\n": types.UpdateBookmarkDocument,
    "\n  mutation DeleteBookmarks($ids: [String!]!) {\n    deleteBookmarks(ids: $ids)\n  }\n": types.DeleteBookmarksDocument,
    "\n  query GetMoodBasedVerse($input: MoodRequestInput!) {\n    getMoodBasedVerse(input: $input) {\n      errors {\n        message\n      }\n      result {\n        verse\n        reference\n        reflection\n        mood\n        fromCache\n        nextRequestAllowed\n      }\n    }\n  }\n": types.GetMoodBasedVerseDocument,
    "\n  query GetSupportedMoods {\n    getSupportedMoods\n  }\n": types.GetSupportedMoodsDocument,
    "\n  query GetUserMoodHistory {\n    getUserMoodHistory {\n      _id\n      userId\n      mood\n      verse\n      reference\n      reflection\n      additionalContext\n      preferredBibleVersion\n      expiresAt\n      createdAt\n      updatedAt\n    }\n  }\n": types.GetUserMoodHistoryDocument,
    "\n  query GetNextMoodRequestTime($mood: String!) {\n    getNextMoodRequestTime(mood: $mood)\n  }\n": types.GetNextMoodRequestTimeDocument,
    "\n  query GetUserNotificationSettingsDetailed {\n    getUserNotificationSettings {\n      errors {\n        message\n      }\n      settings {\n        _id\n        userId\n        enableWebSocketNotifications\n        enableBrowserPushNotifications\n        enableEmailNotifications\n        pushSubscriptionEndpoint\n        pushSubscriptionKeys\n        createdAt\n        updatedAt\n      }\n    }\n  }\n": types.GetUserNotificationSettingsDetailedDocument,
    "\n  mutation UpdateNotificationSettingsDetailed($input: NotificationSettingsInput!) {\n    updateNotificationSettings(input: $input) {\n      errors {\n        message\n      }\n      settings {\n        _id\n        userId\n        enableWebSocketNotifications\n        enableBrowserPushNotifications\n        enableEmailNotifications\n        pushSubscriptionEndpoint\n        pushSubscriptionKeys\n        createdAt\n        updatedAt\n      }\n    }\n  }\n": types.UpdateNotificationSettingsDetailedDocument,
    "\n  mutation ScheduleMoodNotificationDetailed($input: ScheduleNotificationInput!) {\n    scheduleMoodNotification(input: $input) {\n      errors {\n        message\n      }\n      notification {\n        _id\n        userId\n        mood\n        type\n        scheduledFor\n        deviceId\n        message\n        status\n        createdAt\n        updatedAt\n      }\n    }\n  }\n": types.ScheduleMoodNotificationDetailedDocument,
    "\n  query GetUserPendingNotifications {\n    getUserPendingNotifications {\n      _id\n      userId\n      mood\n      type\n      scheduledFor\n      deviceId\n      message\n      status\n      createdAt\n      updatedAt\n    }\n  }\n": types.GetUserPendingNotificationsDocument,
    "\n  mutation CancelNotification($notificationId: String!) {\n    cancelNotification(notificationId: $notificationId)\n  }\n": types.CancelNotificationDocument,
    "\n  subscription MoodRequestAvailableDetailed($userId: String!) {\n    moodRequestAvailable(userId: $userId) {\n      mood\n      message\n      timestamp\n      userId\n    }\n  }\n": types.MoodRequestAvailableDetailedDocument,
    "\n  query GetUserNotificationSettingsBasic {\n    getUserNotificationSettings {\n      errors {\n        message\n      }\n      settings {\n        _id\n        userId\n        enableWebSocketNotifications\n        enableBrowserPushNotifications\n        enableEmailNotifications\n        pushSubscriptionEndpoint\n        pushSubscriptionKeys\n        createdAt\n        updatedAt\n      }\n    }\n  }\n": types.GetUserNotificationSettingsBasicDocument,
    "\n  mutation UpdateNotificationSettingsBasic($input: NotificationSettingsInput!) {\n    updateNotificationSettings(input: $input) {\n      errors {\n        message\n      }\n      settings {\n        _id\n        userId\n        enableWebSocketNotifications\n        enableBrowserPushNotifications\n        enableEmailNotifications\n        pushSubscriptionEndpoint\n        pushSubscriptionKeys\n        createdAt\n        updatedAt\n      }\n    }\n  }\n": types.UpdateNotificationSettingsBasicDocument,
    "\n  mutation ScheduleMoodNotificationBasic($input: ScheduleNotificationInput!) {\n    scheduleMoodNotification(input: $input) {\n      errors {\n        message\n      }\n      notification {\n        _id\n        mood\n        type\n        scheduledFor\n        message\n        status\n      }\n    }\n  }\n": types.ScheduleMoodNotificationBasicDocument,
    "\n  subscription MoodRequestAvailableBasic($userId: String!) {\n    moodRequestAvailable(userId: $userId) {\n      mood\n      message\n      timestamp\n      userId\n    }\n  }\n": types.MoodRequestAvailableBasicDocument,
};

/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query Login($options: UsernamePasswordInput!) {\n        login(options: $options) {\n            user {\n               _id\n                createdAt\n                updatedAt\n                email\n                firstName\n                lastName\n                churchName\n                dob\n                count\n                bioText\n            }\n            errors {\n              field\n              message\n            }\n        }\n    }\n"): (typeof documents)["\n    query Login($options: UsernamePasswordInput!) {\n        login(options: $options) {\n            user {\n               _id\n                createdAt\n                updatedAt\n                email\n                firstName\n                lastName\n                churchName\n                dob\n                count\n                bioText\n            }\n            errors {\n              field\n              message\n            }\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    mutation Register($options: UsernamePasswordInput!) {\n      register(options: $options) {\n        user {\n          _id\n          createdAt\n          updatedAt\n          email\n          firstName\n          lastName\n          churchName\n          dob\n          count\n          bioText\n        }\n        errors {\n          field\n          message\n        }\n      }\n    }\n"): (typeof documents)["\n    mutation Register($options: UsernamePasswordInput!) {\n      register(options: $options) {\n        user {\n          _id\n          createdAt\n          updatedAt\n          email\n          firstName\n          lastName\n          churchName\n          dob\n          count\n          bioText\n        }\n        errors {\n          field\n          message\n        }\n      }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    mutation LoginWithGoogleMutation($options: LogInWithGoogleArgs!) {\n      loginWithGoogle(options: $options) {\n        user {\n          _id\n          createdAt\n          updatedAt\n          email\n          firstName\n          lastName\n          churchName\n          dob\n          count\n          bioText\n        }\n        errors {\n          field\n          message\n        }\n      }\n    }\n"): (typeof documents)["\n    mutation LoginWithGoogleMutation($options: LogInWithGoogleArgs!) {\n      loginWithGoogle(options: $options) {\n        user {\n          _id\n          createdAt\n          updatedAt\n          email\n          firstName\n          lastName\n          churchName\n          dob\n          count\n          bioText\n        }\n        errors {\n          field\n          message\n        }\n      }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query GetListOfLanguages($options: LanguagesArgs!) {\n        getListOfLanguages(options: $options) {\n            data {\n                id\n                glottoId\n                iso\n                name\n                autonym\n                bibles\n                filesets\n                rolvCode\n                countryPopulation\n                translations\n            }\n            meta {\n                pagination {\n                    total\n                    count\n                    perPage\n                    currentPage\n                    totalPages\n                    links\n                    lastPage\n                    nextPageUrl\n                    prevPageUrl\n                    from\n                    to\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query GetListOfLanguages($options: LanguagesArgs!) {\n        getListOfLanguages(options: $options) {\n            data {\n                id\n                glottoId\n                iso\n                name\n                autonym\n                bibles\n                filesets\n                rolvCode\n                countryPopulation\n                translations\n            }\n            meta {\n                pagination {\n                    total\n                    count\n                    perPage\n                    currentPage\n                    totalPages\n                    links\n                    lastPage\n                    nextPageUrl\n                    prevPageUrl\n                    from\n                    to\n                }\n            }\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query SearchLangueages($options: SearchLanguageArgs!) {\n    searchListOfLanguages(options: $options) {\n      data {\n        id\n        glottoId\n        iso\n        name\n        autonym\n        bibles\n        rolvCode\n      }\n      meta {\n        pagination {\n          total\n          count\n          perPage\n          currentPage\n          totalPages\n          links\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query SearchLangueages($options: SearchLanguageArgs!) {\n    searchListOfLanguages(options: $options) {\n      data {\n        id\n        glottoId\n        iso\n        name\n        autonym\n        bibles\n        rolvCode\n      }\n      meta {\n        pagination {\n          total\n          count\n          perPage\n          currentPage\n          totalPages\n          links\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query GetListOfBibles($options: BibleArgs!) {\n        getListOFBibles(options: $options){\n            data {\n                name\n                vname\n                abbr\n                language\n                autonym\n                languageId\n                iso\n                date\n                filesets\n            }\n            meta {\n                pagination {\n                    total\n                    count\n                    from\n                    to\n                    nextPageUrl\n                    perPage\n                    prevPageUrl\n                    totalPages\n                    lastPage\n                    currentPage\n                    links\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query GetListOfBibles($options: BibleArgs!) {\n        getListOFBibles(options: $options){\n            data {\n                name\n                vname\n                abbr\n                language\n                autonym\n                languageId\n                iso\n                date\n                filesets\n            }\n            meta {\n                pagination {\n                    total\n                    count\n                    from\n                    to\n                    nextPageUrl\n                    perPage\n                    prevPageUrl\n                    totalPages\n                    lastPage\n                    currentPage\n                    links\n                }\n            }\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query GetListOfBooksFromBible($options: BookArgs!) {\n        getListOfBooksForBible(options: $options) {\n            data {\n                bookId\n                bookIdUsfx\n                bookIdOsis\n                name\n                testament\n                testamentOrder\n                bookOrder\n                bookGroup\n                nameShort\n                chapters\n                contentTypes\n            }\n        }\n    }\n"): (typeof documents)["\n    query GetListOfBooksFromBible($options: BookArgs!) {\n        getListOfBooksForBible(options: $options) {\n            data {\n                bookId\n                bookIdUsfx\n                bookIdOsis\n                name\n                testament\n                testamentOrder\n                bookOrder\n                bookGroup\n                nameShort\n                chapters\n                contentTypes\n            }\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query GetListOfVerseFromBookChapter($options: VerseArgs!) {\n        getListOfVerseFromBookChapter(options: $options){\n            data {\n                bookId\n                bookName\n                bookNameAlt\n                chapter\n                chapterAlt\n                verseStart\n                verseStartAlt\n                verseEnd\n                verseEndAlt\n                verseText\n            } \n        }\n    }\n"): (typeof documents)["\n    query GetListOfVerseFromBookChapter($options: VerseArgs!) {\n        getListOfVerseFromBookChapter(options: $options){\n            data {\n                bookId\n                bookName\n                bookNameAlt\n                chapter\n                chapterAlt\n                verseStart\n                verseStartAlt\n                verseEnd\n                verseEndAlt\n                verseText\n            } \n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetCopyRightByBibleId($options: CopyrightArgs!) {\n    getCopyRightByBibleId(options: $options) {\n      data {\n        id\n        asset_id\n        type\n        size\n        copyright {\n          copyright_date\n          copyright\n          copyright_description\n          created_at\n          updated_at\n          open_access\n          organizations {\n            id\n            slug\n            abbreviation\n            primaryColor\n            secondaryColor\n            inactive\n            url_facebook\n            url_website\n            url_donate\n            url_twitter\n            address\n            address2\n            city\n            state\n            country\n            zip\n            phone\n            email\n            email_director\n            latitude\n            longitude\n            laravel_through_key\n            logos {\n              language_id\n              language_iso\n              url\n              icon\n            }\n            translations {\n              language_id\n              vernacular\n              alt\n              name\n              description_short\n            }\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetCopyRightByBibleId($options: CopyrightArgs!) {\n    getCopyRightByBibleId(options: $options) {\n      data {\n        id\n        asset_id\n        type\n        size\n        copyright {\n          copyright_date\n          copyright\n          copyright_description\n          created_at\n          updated_at\n          open_access\n          organizations {\n            id\n            slug\n            abbreviation\n            primaryColor\n            secondaryColor\n            inactive\n            url_facebook\n            url_website\n            url_donate\n            url_twitter\n            address\n            address2\n            city\n            state\n            country\n            zip\n            phone\n            email\n            email_director\n            latitude\n            longitude\n            laravel_through_key\n            logos {\n              language_id\n              language_iso\n              url\n              icon\n            }\n            translations {\n              language_id\n              vernacular\n              alt\n              name\n              description_short\n            }\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetAudioMedia($options: AudioMediaArgs!) {\n    getAudioMedia(options: $options) {\n      data {\n        book_id\n        book_name\n        chapter_start\n        chapter_end\n        verse_start\n        verse_end\n        thumbnail\n        timestamp\n        path\n        duration\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetAudioMedia($options: AudioMediaArgs!) {\n    getAudioMedia(options: $options) {\n      data {\n        book_id\n        book_name\n        chapter_start\n        chapter_end\n        verse_start\n        verse_end\n        thumbnail\n        timestamp\n        path\n        duration\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetMediaTimestamps($options: AudioMediaArgs!) {\n    getMediaTimestamps(options: $options) {\n      data {\n        book\n        chapter\n        verse_start\n        timestamp\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetMediaTimestamps($options: AudioMediaArgs!) {\n    getMediaTimestamps(options: $options) {\n      data {\n        book\n        chapter\n        verse_start\n        timestamp\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetTranslations {\n    getTranslations {\n      _id\n      name\n      abbreviation\n      language\n      lang\n      books {\n        bookName\n        bibleId\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetTranslations {\n    getTranslations {\n      _id\n      name\n      abbreviation\n      language\n      lang\n      books {\n        bookName\n        bibleId\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetBooks($translationId: String!) {\n    getBooks(translationId: $translationId) {\n      bookName\n      bibleId\n    }\n  }\n"): (typeof documents)["\n  query GetBooks($translationId: String!) {\n    getBooks(translationId: $translationId) {\n      bookName\n      bibleId\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetBookById($bibleId: String!) {\n  getBookById(bibleId: $bibleId) {\n    _id\n    bookName\n    bibleId\n    chapters {\n      chapterName\n      bibleId\n    }\n    translation {\n      abbreviation\n      name\n    }\n  }\n}\n"): (typeof documents)["\n  query GetBookById($bibleId: String!) {\n  getBookById(bibleId: $bibleId) {\n    _id\n    bookName\n    bibleId\n    chapters {\n      chapterName\n      bibleId\n    }\n    translation {\n      abbreviation\n      name\n    }\n  }\n}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetChapter($bibleId: String!) {\n    getChapter(bibleId: $bibleId) {\n      _id\n      chapterNumber\n      bibleId\n      bookName\n      verses {\n        verse\n        bibleId\n        text\n      }\n      translation {\n        abbreviation\n        name\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetChapter($bibleId: String!) {\n    getChapter(bibleId: $bibleId) {\n      _id\n      chapterNumber\n      bibleId\n      bookName\n      verses {\n        verse\n        bibleId\n        text\n      }\n      translation {\n        abbreviation\n        name\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetVerseById($bibleId: String!) {\n    getVerseByBibleId(bibleId: $bibleId) {\n      _id\n      translation {\n        name\n        abbreviation\n      }\n      bookName\n      chapterNumber\n      verse\n      text\n      bibleId\n    }\n  }\n"): (typeof documents)["\n  query GetVerseById($bibleId: String!) {\n    getVerseByBibleId(bibleId: $bibleId) {\n      _id\n      translation {\n        name\n        abbreviation\n      }\n      bookName\n      chapterNumber\n      verse\n      text\n      bibleId\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation SetUserHistory($options: HistoryOptions!) {\n    setUserHistory(options: $options) {\n      errors {\n        field\n        message\n      }\n      results\n    }\n  }\n"): (typeof documents)["\n  mutation SetUserHistory($options: HistoryOptions!) {\n    setUserHistory(options: $options) {\n      errors {\n        field\n        message\n      }\n      results\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetMedia($id: String!) {\n    getMedia(id: $id) {\n      _id\n      fileKey\n      filename\n      mimeType\n      size\n      purpose\n      isPublic\n      description\n      owner {\n        _id\n      }\n      cache {\n        url\n        expiresAt\n        duration\n      }\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  query GetMedia($id: String!) {\n    getMedia(id: $id) {\n      _id\n      fileKey\n      filename\n      mimeType\n      size\n      purpose\n      isPublic\n      description\n      owner {\n        _id\n      }\n      cache {\n        url\n        expiresAt\n        duration\n      }\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetMediaByPurpose($purpose: String!) {\n    getMediaByPurpose(purpose: $purpose) {\n      _id\n      fileKey\n      filename\n      mimeType\n      size\n      purpose\n      isPublic\n      description\n      owner {\n        _id\n      }\n      cache {\n        url\n        expiresAt\n        duration\n      }\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  query GetMediaByPurpose($purpose: String!) {\n    getMediaByPurpose(purpose: $purpose) {\n      _id\n      fileKey\n      filename\n      mimeType\n      size\n      purpose\n      isPublic\n      description\n      owner {\n        _id\n      }\n      cache {\n        url\n        expiresAt\n        duration\n      }\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetMediaUrl($fileKey: String!) {\n    getMediaUrl(fileKey: $fileKey) {\n      signedUrl\n      errors {\n        field\n        message\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetMediaUrl($fileKey: String!) {\n    getMediaUrl(fileKey: $fileKey) {\n      signedUrl\n      errors {\n        field\n        message\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation GetGetSignedUrl($options: SignedUrlInput!) {\n    getGetSignedUrl(options: $options) {\n      signedUrl\n      fileKey\n      errors {\n        field\n        message\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation GetGetSignedUrl($options: SignedUrlInput!) {\n    getGetSignedUrl(options: $options) {\n      signedUrl\n      fileKey\n      errors {\n        field\n        message\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation GetPostSignedUrl($options: SignedUrlInput!) {\n    getPostSignedUrl(options: $options) {\n      signedUrl\n      fields\n      fileKey\n      errors {\n        field\n        message\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation GetPostSignedUrl($options: SignedUrlInput!) {\n    getPostSignedUrl(options: $options) {\n      signedUrl\n      fields\n      fileKey\n      errors {\n        field\n        message\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation CreateMedia($options: MediaInput!) {\n    createMedia(options: $options) {\n      results {\n        _id\n        fileKey\n        filename\n        mimeType\n        size\n        purpose\n        isPublic\n        description\n        owner {\n          _id\n        }\n        cache {\n          url\n          expiresAt\n          duration\n        }\n        createdAt\n        updatedAt\n      }\n      errors {\n        field\n        message\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation CreateMedia($options: MediaInput!) {\n    createMedia(options: $options) {\n      results {\n        _id\n        fileKey\n        filename\n        mimeType\n        size\n        purpose\n        isPublic\n        description\n        owner {\n          _id\n        }\n        cache {\n          url\n          expiresAt\n          duration\n        }\n        createdAt\n        updatedAt\n      }\n      errors {\n        field\n        message\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation UpdateMedia($id: String!, $options: MediaInput!) {\n    updateMedia(id: $id, options: $options) {\n      results {\n        _id\n        fileKey\n        filename\n        mimeType\n        size\n        purpose\n        isPublic\n        description\n        owner {\n          _id\n        }\n        cache {\n          url\n          expiresAt\n          duration\n        }\n        createdAt\n        updatedAt\n      }\n      errors {\n        field\n        message\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation UpdateMedia($id: String!, $options: MediaInput!) {\n    updateMedia(id: $id, options: $options) {\n      results {\n        _id\n        fileKey\n        filename\n        mimeType\n        size\n        purpose\n        isPublic\n        description\n        owner {\n          _id\n        }\n        cache {\n          url\n          expiresAt\n          duration\n        }\n        createdAt\n        updatedAt\n      }\n      errors {\n        field\n        message\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation DeleteMedia($id: String!) {\n    deleteMedia(id: $id) {\n      results {\n        _id\n        fileKey\n        filename\n        mimeType\n        size\n        purpose\n        isPublic\n        description\n        owner {\n          _id\n        }\n        cache {\n          url\n          expiresAt\n          duration\n        }\n        createdAt\n        updatedAt\n      }\n      errors {\n        field\n        message\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation DeleteMedia($id: String!) {\n    deleteMedia(id: $id) {\n      results {\n        _id\n        fileKey\n        filename\n        mimeType\n        size\n        purpose\n        isPublic\n        description\n        owner {\n          _id\n        }\n        cache {\n          url\n          expiresAt\n          duration\n        }\n        createdAt\n        updatedAt\n      }\n      errors {\n        field\n        message\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetNFCConfig($id: String!) {\n    getNFCConfig(id: $id) {\n      results {\n        _id\n        owner {\n          _id\n        }\n        nfcIds\n        tiles {\n          id\n          type\n          label\n          icon\n          url\n          size\n          position {\n            x\n            y\n          }\n          color\n          subtitle\n          isInDock\n        }\n        wallpaper\n        createdAt\n        updatedAt\n      }\n      errors {\n        field\n        message\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetNFCConfig($id: String!) {\n    getNFCConfig(id: $id) {\n      results {\n        _id\n        owner {\n          _id\n        }\n        nfcIds\n        tiles {\n          id\n          type\n          label\n          icon\n          url\n          size\n          position {\n            x\n            y\n          }\n          color\n          subtitle\n          isInDock\n        }\n        wallpaper\n        createdAt\n        updatedAt\n      }\n      errors {\n        field\n        message\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetNFCConfigByOwner($ownerId: String!) {\n    getNFCConfigByOwner(ownerId: $ownerId) {\n      results {\n        _id\n        owner {\n          _id\n        }\n        nfcIds\n        tiles {\n          id\n          type\n          label\n          icon\n          url\n          size\n          position {\n            x\n            y\n          }\n          color\n          subtitle\n          isInDock\n        }\n        wallpaper\n        createdAt\n        updatedAt\n      }\n      errors {\n        field\n        message\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetNFCConfigByOwner($ownerId: String!) {\n    getNFCConfigByOwner(ownerId: $ownerId) {\n      results {\n        _id\n        owner {\n          _id\n        }\n        nfcIds\n        tiles {\n          id\n          type\n          label\n          icon\n          url\n          size\n          position {\n            x\n            y\n          }\n          color\n          subtitle\n          isInDock\n        }\n        wallpaper\n        createdAt\n        updatedAt\n      }\n      errors {\n        field\n        message\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation CreateNFCConfig($options: NFCConfigInput!) {\n    createNFCConfig(options: $options) {\n      results {\n        _id\n        owner {\n          _id\n        }\n        nfcIds\n        tiles {\n          id\n          type\n          label\n          icon\n          url\n          size\n          position {\n            x\n            y\n          }\n          color\n          subtitle\n          isInDock\n        }\n        wallpaper\n        createdAt\n        updatedAt\n      }\n      errors {\n        field\n        message\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation CreateNFCConfig($options: NFCConfigInput!) {\n    createNFCConfig(options: $options) {\n      results {\n        _id\n        owner {\n          _id\n        }\n        nfcIds\n        tiles {\n          id\n          type\n          label\n          icon\n          url\n          size\n          position {\n            x\n            y\n          }\n          color\n          subtitle\n          isInDock\n        }\n        wallpaper\n        createdAt\n        updatedAt\n      }\n      errors {\n        field\n        message\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation UpdateNFCConfig($id: String!, $options: NFCConfigInput!) {\n    updateNFCConfig(id: $id, options: $options) {\n      results {\n        _id\n        owner {\n          _id\n        }\n        nfcIds\n        tiles {\n          id\n          type\n          label\n          icon\n          url\n          size\n          position {\n            x\n            y\n          }\n          color\n          subtitle\n          isInDock\n        }\n        wallpaper\n        createdAt\n        updatedAt\n      }\n      errors {\n        field\n        message\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation UpdateNFCConfig($id: String!, $options: NFCConfigInput!) {\n    updateNFCConfig(id: $id, options: $options) {\n      results {\n        _id\n        owner {\n          _id\n        }\n        nfcIds\n        tiles {\n          id\n          type\n          label\n          icon\n          url\n          size\n          position {\n            x\n            y\n          }\n          color\n          subtitle\n          isInDock\n        }\n        wallpaper\n        createdAt\n        updatedAt\n      }\n      errors {\n        field\n        message\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation UpdateNFCTiles($id: String!, $tiles: [TileConfigInput!]!, $wallpaper: String) {\n    updateNFCTiles(id: $id, tiles: $tiles, wallpaper: $wallpaper) {\n      results {\n        _id\n        tiles {\n          id\n          type\n          label\n          icon\n          url\n          size\n          position {\n            x\n            y\n          }\n          color\n          subtitle\n          isInDock\n        }\n        wallpaper\n      }\n      errors {\n        field\n        message\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation UpdateNFCTiles($id: String!, $tiles: [TileConfigInput!]!, $wallpaper: String) {\n    updateNFCTiles(id: $id, tiles: $tiles, wallpaper: $wallpaper) {\n      results {\n        _id\n        tiles {\n          id\n          type\n          label\n          icon\n          url\n          size\n          position {\n            x\n            y\n          }\n          color\n          subtitle\n          isInDock\n        }\n        wallpaper\n      }\n      errors {\n        field\n        message\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation DeleteNFCConfig($id: String!) {\n    deleteNFCConfig(id: $id) {\n      results {\n        _id\n        owner {\n          _id\n        }\n        nfcIds\n        createdAt\n        updatedAt\n      }\n      errors {\n        field\n        message\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation DeleteNFCConfig($id: String!) {\n    deleteNFCConfig(id: $id) {\n      results {\n        _id\n        owner {\n          _id\n        }\n        nfcIds\n        createdAt\n        updatedAt\n      }\n      errors {\n        field\n        message\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query OpenAi($options: GptArgs!) {\n        getOpen(options: $options)\n    }\n"): (typeof documents)["\n    query OpenAi($options: GptArgs!) {\n        getOpen(options: $options)\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  subscription Subscription($deviceId: String!) {\n    aiChatReponseUpdated(deviceId: $deviceId)\n  }\n"): (typeof documents)["\n  subscription Subscription($deviceId: String!) {\n    aiChatReponseUpdated(deviceId: $deviceId)\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetSermons {\n    getSermons {\n      results {\n        _id\n        title\n        content\n        status\n        createdAt\n        updatedAt\n        author {\n          _id\n          firstName\n          lastName\n        }\n      }\n      errors {\n        field\n        message\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetSermons {\n    getSermons {\n      results {\n        _id\n        title\n        content\n        status\n        createdAt\n        updatedAt\n        author {\n          _id\n          firstName\n          lastName\n        }\n      }\n      errors {\n        field\n        message\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetSermon($id: String!) {\n    getSermon(id: $id) {\n      results {\n        _id\n        title\n        content\n        status\n        createdAt\n        updatedAt\n        author {\n          _id\n          firstName\n          lastName\n        }\n      }\n      errors {\n        field\n        message\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetSermon($id: String!) {\n    getSermon(id: $id) {\n      results {\n        _id\n        title\n        content\n        status\n        createdAt\n        updatedAt\n        author {\n          _id\n          firstName\n          lastName\n        }\n      }\n      errors {\n        field\n        message\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation CreateSermon($options: SermonInput!) {\n    createSermon(options: $options) {\n      results {\n        _id\n        title\n        content\n        status\n        createdAt\n        updatedAt\n        author {\n          _id\n          firstName\n          lastName\n        }\n      }\n      errors {\n        field\n        message\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation CreateSermon($options: SermonInput!) {\n    createSermon(options: $options) {\n      results {\n        _id\n        title\n        content\n        status\n        createdAt\n        updatedAt\n        author {\n          _id\n          firstName\n          lastName\n        }\n      }\n      errors {\n        field\n        message\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation UpdateSermon($id: String!, $options: SermonInput!) {\n    updateSermon(id: $id, options: $options) {\n      results {\n        _id\n        title\n        content\n        status\n        createdAt\n        updatedAt\n        author {\n          _id\n          firstName\n          lastName\n        }\n      }\n      errors {\n        field\n        message\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation UpdateSermon($id: String!, $options: SermonInput!) {\n    updateSermon(id: $id, options: $options) {\n      results {\n        _id\n        title\n        content\n        status\n        createdAt\n        updatedAt\n        author {\n          _id\n          firstName\n          lastName\n        }\n      }\n      errors {\n        field\n        message\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation DeleteSermon($id: String!) {\n    deleteSermon(id: $id) {\n      results {\n        _id\n        title\n      }\n      errors {\n        field\n        message\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation DeleteSermon($id: String!) {\n    deleteSermon(id: $id) {\n      results {\n        _id\n        title\n      }\n      errors {\n        field\n        message\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation GenerateSermonContent($input: SermonAIInput!) {\n    generateSermonContent(input: $input) {\n      result {\n        content\n        suggestions\n        relatedVerses\n        promptType\n      }\n      errors {\n        message\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation GenerateSermonContent($input: SermonAIInput!) {\n    generateSermonContent(input: $input) {\n      result {\n        content\n        suggestions\n        relatedVerses\n        promptType\n      }\n      errors {\n        message\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetSermonAIPromptTypes {\n    getSermonAIPromptTypes {\n      type\n      category\n      label\n      description\n    }\n  }\n"): (typeof documents)["\n  query GetSermonAIPromptTypes {\n    getSermonAIPromptTypes {\n      type\n      category\n      label\n      description\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation StreamSermonContent($input: SermonAIInput!) {\n    streamSermonContent(input: $input)\n  }\n"): (typeof documents)["\n  mutation StreamSermonContent($input: SermonAIInput!) {\n    streamSermonContent(input: $input)\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  subscription SermonAIStream($sessionId: String!) {\n    sermonAIStream(sessionId: $sessionId)\n  }\n"): (typeof documents)["\n  subscription SermonAIStream($sessionId: String!) {\n    sermonAIStream(sessionId: $sessionId)\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query Me {\n        me {\n            user {\n              _id\n              createdAt\n              updatedAt\n              email\n              firstName\n              lastName\n              churchName\n              bioText\n              dob\n              count\n            }\n        }\n    }\n"): (typeof documents)["\n    query Me {\n        me {\n            user {\n              _id\n              createdAt\n              updatedAt\n              email\n              firstName\n              lastName\n              churchName\n              bioText\n              dob\n              count\n            }\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query UserBibleHistoryQuery {\n        me {\n          user{\n            bibleHistory {\n              _id\n              history {\n                language\n                bibleAbbr\n                bookId\n                chapterNumber\n                viewedAt\n              }\n              current\n              createdAt\n              updatedAt\n            }\n          }\n        }\n    }\n"): (typeof documents)["\n    query UserBibleHistoryQuery {\n        me {\n          user{\n            bibleHistory {\n              _id\n              history {\n                language\n                bibleAbbr\n                bookId\n                chapterNumber\n                viewedAt\n              }\n              current\n              createdAt\n              updatedAt\n            }\n          }\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query getBookmarks {\n    getMyBookmarks {\n      results {\n        _id\n        createdAt\n        updatedAt\n        author {\n          _id\n        }\n        bibleId\n        newVerses {\n          bookId\n          bookName\n          bookNameAlt\n          chapter\n          chapterAlt\n          verseStart\n          verseStartAlt\n          verseEnd\n          verseEndAlt\n          verseText\n        }\n        verses {\n          _id\n          translation {\n            name\n            abbreviation\n          }\n          bookName\n          chapterNumber\n          verse\n          text\n          bibleId\n        }\n        note\n      }\n    }\n  }\n"): (typeof documents)["\n  query getBookmarks {\n    getMyBookmarks {\n      results {\n        _id\n        createdAt\n        updatedAt\n        author {\n          _id\n        }\n        bibleId\n        newVerses {\n          bookId\n          bookName\n          bookNameAlt\n          chapter\n          chapterAlt\n          verseStart\n          verseStartAlt\n          verseEnd\n          verseEndAlt\n          verseText\n        }\n        verses {\n          _id\n          translation {\n            name\n            abbreviation\n          }\n          bookName\n          chapterNumber\n          verse\n          text\n          bibleId\n        }\n        note\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation CreateBookmark($options: BookmarkOptions!) {\n    createBookmark(options: $options) {\n      results {\n        _id\n        createdAt\n        updatedAt\n        author {\n          _id\n          createdAt\n          updatedAt\n          email\n          firstName\n          lastName\n          churchName\n          dob\n          count\n          bookmarks {\n            _id\n            createdAt\n            updatedAt\n            bibleId\n            note\n          }\n          bioText\n        }\n        bibleId\n        newVerses {\n          bookId\n          bookName\n          bookNameAlt\n          chapter\n          chapterAlt\n          verseStart\n          verseStartAlt\n          verseEnd\n          verseEndAlt\n          verseText\n        }\n        verses {\n          _id\n          translation {\n            name\n            abbreviation\n          }\n          bookName\n          chapterNumber\n          verse\n          text\n          bibleId\n        }\n        note\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation CreateBookmark($options: BookmarkOptions!) {\n    createBookmark(options: $options) {\n      results {\n        _id\n        createdAt\n        updatedAt\n        author {\n          _id\n          createdAt\n          updatedAt\n          email\n          firstName\n          lastName\n          churchName\n          dob\n          count\n          bookmarks {\n            _id\n            createdAt\n            updatedAt\n            bibleId\n            note\n          }\n          bioText\n        }\n        bibleId\n        newVerses {\n          bookId\n          bookName\n          bookNameAlt\n          chapter\n          chapterAlt\n          verseStart\n          verseStartAlt\n          verseEnd\n          verseEndAlt\n          verseText\n        }\n        verses {\n          _id\n          translation {\n            name\n            abbreviation\n          }\n          bookName\n          chapterNumber\n          verse\n          text\n          bibleId\n        }\n        note\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation UpdateUser($options: UserUpdateInput!) {\n    updateUser(options: $options) {\n      user {\n        _id\n        createdAt\n        updatedAt\n        email\n        firstName\n        lastName\n        churchName\n        bioText\n        dob\n        count\n      }\n      errors {\n        field\n        message\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation UpdateUser($options: UserUpdateInput!) {\n    updateUser(options: $options) {\n      user {\n        _id\n        createdAt\n        updatedAt\n        email\n        firstName\n        lastName\n        churchName\n        bioText\n        dob\n        count\n      }\n      errors {\n        field\n        message\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation UpdateBookmark($updateBookmarkId: String!, $options: BookmarkOptions!) {\n    updateBookmark(id: $updateBookmarkId, options: $options) {\n      errors {\n        field\n        message\n      }\n      results {\n        _id\n        createdAt\n        updatedAt\n        author {\n          _id\n        }\n        note\n        verses {\n          _id\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation UpdateBookmark($updateBookmarkId: String!, $options: BookmarkOptions!) {\n    updateBookmark(id: $updateBookmarkId, options: $options) {\n      errors {\n        field\n        message\n      }\n      results {\n        _id\n        createdAt\n        updatedAt\n        author {\n          _id\n        }\n        note\n        verses {\n          _id\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation DeleteBookmarks($ids: [String!]!) {\n    deleteBookmarks(ids: $ids)\n  }\n"): (typeof documents)["\n  mutation DeleteBookmarks($ids: [String!]!) {\n    deleteBookmarks(ids: $ids)\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetMoodBasedVerse($input: MoodRequestInput!) {\n    getMoodBasedVerse(input: $input) {\n      errors {\n        message\n      }\n      result {\n        verse\n        reference\n        reflection\n        mood\n        fromCache\n        nextRequestAllowed\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetMoodBasedVerse($input: MoodRequestInput!) {\n    getMoodBasedVerse(input: $input) {\n      errors {\n        message\n      }\n      result {\n        verse\n        reference\n        reflection\n        mood\n        fromCache\n        nextRequestAllowed\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetSupportedMoods {\n    getSupportedMoods\n  }\n"): (typeof documents)["\n  query GetSupportedMoods {\n    getSupportedMoods\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetUserMoodHistory {\n    getUserMoodHistory {\n      _id\n      userId\n      mood\n      verse\n      reference\n      reflection\n      additionalContext\n      preferredBibleVersion\n      expiresAt\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  query GetUserMoodHistory {\n    getUserMoodHistory {\n      _id\n      userId\n      mood\n      verse\n      reference\n      reflection\n      additionalContext\n      preferredBibleVersion\n      expiresAt\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetNextMoodRequestTime($mood: String!) {\n    getNextMoodRequestTime(mood: $mood)\n  }\n"): (typeof documents)["\n  query GetNextMoodRequestTime($mood: String!) {\n    getNextMoodRequestTime(mood: $mood)\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetUserNotificationSettingsDetailed {\n    getUserNotificationSettings {\n      errors {\n        message\n      }\n      settings {\n        _id\n        userId\n        enableWebSocketNotifications\n        enableBrowserPushNotifications\n        enableEmailNotifications\n        pushSubscriptionEndpoint\n        pushSubscriptionKeys\n        createdAt\n        updatedAt\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetUserNotificationSettingsDetailed {\n    getUserNotificationSettings {\n      errors {\n        message\n      }\n      settings {\n        _id\n        userId\n        enableWebSocketNotifications\n        enableBrowserPushNotifications\n        enableEmailNotifications\n        pushSubscriptionEndpoint\n        pushSubscriptionKeys\n        createdAt\n        updatedAt\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation UpdateNotificationSettingsDetailed($input: NotificationSettingsInput!) {\n    updateNotificationSettings(input: $input) {\n      errors {\n        message\n      }\n      settings {\n        _id\n        userId\n        enableWebSocketNotifications\n        enableBrowserPushNotifications\n        enableEmailNotifications\n        pushSubscriptionEndpoint\n        pushSubscriptionKeys\n        createdAt\n        updatedAt\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation UpdateNotificationSettingsDetailed($input: NotificationSettingsInput!) {\n    updateNotificationSettings(input: $input) {\n      errors {\n        message\n      }\n      settings {\n        _id\n        userId\n        enableWebSocketNotifications\n        enableBrowserPushNotifications\n        enableEmailNotifications\n        pushSubscriptionEndpoint\n        pushSubscriptionKeys\n        createdAt\n        updatedAt\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation ScheduleMoodNotificationDetailed($input: ScheduleNotificationInput!) {\n    scheduleMoodNotification(input: $input) {\n      errors {\n        message\n      }\n      notification {\n        _id\n        userId\n        mood\n        type\n        scheduledFor\n        deviceId\n        message\n        status\n        createdAt\n        updatedAt\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation ScheduleMoodNotificationDetailed($input: ScheduleNotificationInput!) {\n    scheduleMoodNotification(input: $input) {\n      errors {\n        message\n      }\n      notification {\n        _id\n        userId\n        mood\n        type\n        scheduledFor\n        deviceId\n        message\n        status\n        createdAt\n        updatedAt\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetUserPendingNotifications {\n    getUserPendingNotifications {\n      _id\n      userId\n      mood\n      type\n      scheduledFor\n      deviceId\n      message\n      status\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  query GetUserPendingNotifications {\n    getUserPendingNotifications {\n      _id\n      userId\n      mood\n      type\n      scheduledFor\n      deviceId\n      message\n      status\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation CancelNotification($notificationId: String!) {\n    cancelNotification(notificationId: $notificationId)\n  }\n"): (typeof documents)["\n  mutation CancelNotification($notificationId: String!) {\n    cancelNotification(notificationId: $notificationId)\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  subscription MoodRequestAvailableDetailed($userId: String!) {\n    moodRequestAvailable(userId: $userId) {\n      mood\n      message\n      timestamp\n      userId\n    }\n  }\n"): (typeof documents)["\n  subscription MoodRequestAvailableDetailed($userId: String!) {\n    moodRequestAvailable(userId: $userId) {\n      mood\n      message\n      timestamp\n      userId\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetUserNotificationSettingsBasic {\n    getUserNotificationSettings {\n      errors {\n        message\n      }\n      settings {\n        _id\n        userId\n        enableWebSocketNotifications\n        enableBrowserPushNotifications\n        enableEmailNotifications\n        pushSubscriptionEndpoint\n        pushSubscriptionKeys\n        createdAt\n        updatedAt\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetUserNotificationSettingsBasic {\n    getUserNotificationSettings {\n      errors {\n        message\n      }\n      settings {\n        _id\n        userId\n        enableWebSocketNotifications\n        enableBrowserPushNotifications\n        enableEmailNotifications\n        pushSubscriptionEndpoint\n        pushSubscriptionKeys\n        createdAt\n        updatedAt\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation UpdateNotificationSettingsBasic($input: NotificationSettingsInput!) {\n    updateNotificationSettings(input: $input) {\n      errors {\n        message\n      }\n      settings {\n        _id\n        userId\n        enableWebSocketNotifications\n        enableBrowserPushNotifications\n        enableEmailNotifications\n        pushSubscriptionEndpoint\n        pushSubscriptionKeys\n        createdAt\n        updatedAt\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation UpdateNotificationSettingsBasic($input: NotificationSettingsInput!) {\n    updateNotificationSettings(input: $input) {\n      errors {\n        message\n      }\n      settings {\n        _id\n        userId\n        enableWebSocketNotifications\n        enableBrowserPushNotifications\n        enableEmailNotifications\n        pushSubscriptionEndpoint\n        pushSubscriptionKeys\n        createdAt\n        updatedAt\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation ScheduleMoodNotificationBasic($input: ScheduleNotificationInput!) {\n    scheduleMoodNotification(input: $input) {\n      errors {\n        message\n      }\n      notification {\n        _id\n        mood\n        type\n        scheduledFor\n        message\n        status\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation ScheduleMoodNotificationBasic($input: ScheduleNotificationInput!) {\n    scheduleMoodNotification(input: $input) {\n      errors {\n        message\n      }\n      notification {\n        _id\n        mood\n        type\n        scheduledFor\n        message\n        status\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  subscription MoodRequestAvailableBasic($userId: String!) {\n    moodRequestAvailable(userId: $userId) {\n      mood\n      message\n      timestamp\n      userId\n    }\n  }\n"): (typeof documents)["\n  subscription MoodRequestAvailableBasic($userId: String!) {\n    moodRequestAvailable(userId: $userId) {\n      mood\n      message\n      timestamp\n      userId\n    }\n  }\n"];

/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = gql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
**/
export function gql(source: string): unknown;

export function gql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;